[package]
name = "communicator"
version = "0.1.0"
authors = ["Evan Dickinson <me@evand.name>"]
edition = "2018"

[dependencies]
nom = "^4.0"
smallvec = "^0.6"
error-chain = "0.12.0"
itertools = "0.8.0"
